apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: config-content
              mountPath: /usr/share/nginx/html/index.html
              subPath: index.html
            # This is a PersistentVolume.
            - name: persistent-data
              mountPath: /usr/share/nginx/html/data
          env:
          - name: API_KEY
            valueFrom:
              secretKeyRef:
                name: app-secret
                key: API_KEY
      volumes:
        - name: config-content
          configMap:
            name: web-content
        # This is a PersistentVolumeClaim.
        - name: persistent-data
          persistentVolumeClaim:
            claimName: web-pvc
